name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.11.6]
        architecture: [x86_64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install pyinstaller wxpython setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.architecture }} --icon=Assets/soh.ico "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: dist

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.11.6]
        architecture: [arm64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install pyinstaller wxpython setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.architecture }} --icon=Assets/soh.icns "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries-${{ matrix.architecture }}
        path: dist

  build-linux:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.11.6]
        architecture: [x86_64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev libnotify-dev freeglut3 freeglut3-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgstreamer-gl1.0-dev libgconf-2-4 libsm6 libxext6 libxrender1 python3-dev
        pip3 install --upgrade --pre -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython
        pip install pyinstaller wxpython setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.architecture }} --icon=Assets/soh.png "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: dist
