name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]
        architecture: [x86_64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxPython base64 setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.architecture }} "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: dist
