name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.11.6]
        architecture: [x86_64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install pyinstaller wxpython setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.architecture }} "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: dist

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.11.6]
        architecture: [x86_64, arm64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install pyinstaller wxpython setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.architecture }} "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries-${{ matrix.architecture }}
        path: dist
