name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]
        architecture: [x86, x86_64, aarch64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxPython base64 setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.os }}-${{ matrix.architecture }} "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-binaries
        path: dist
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.11]
        architecture: [x86, x86_64, aarch64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxPython base64 setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.os }}-${{ matrix.architecture }} "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-binaries
        path: dist

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.11]
        architecture: [x86, x86_64, aarch64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxPython base64 setproctitle

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --distpath dist/${{ matrix.os }}-${{ matrix.architecture }} "SoH Mod Organizer.py"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-binaries
        path: dist
